language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "nightly"
# command to install dependencies
before_install:
  - "git clone https://github.com/pmaupin/static_pdfs tests/static_pdfs"
install:
  - "pip install ."
# command to run tests
script: "cd tests; py.test"
